coverage:
  status:
    project:
      default:
        informational: false
    patch:
      default:
        informational: false

ignore:
  - "src/remote_debugging/offsets/v_*.rs"
  - "tests/"

flag_management:
  default_rules:
    carryforward: true

codecov:
  allow_pseudo_compare: False # the default is true
