// Generated by gen-offsets-table.py for CPython 3.15.0a7
// Version hex: 0x030f00a7

use crate::remote_debugging::offsets::offset_table::DebugOffsetsLayout;

pub const LAYOUT: DebugOffsetsLayout = DebugOffsetsLayout {
    version_hex: 0x030f00a7,
    runtime_interpreters_head: 40,
    interp_id: 56,
    interp_next: 64,
    interp_threads_head: 72,
    interp_gc: 88,
    thread_interp: 200,
    gc_size: 704,
    gc_collecting: 712,
    gc_frame: Some(720),
    gc_generation_stats_size: None,
    gc_generation_stats: None,
};
