// Generated by gen-offsets-table.py for CPython 3.15.0b1+
// Version hex: 0x030f00b1

use crate::remote_debugging::offsets::offset_table::DebugOffsetsLayout;

pub const LAYOUT: DebugOffsetsLayout = DebugOffsetsLayout {
    version_hex: 0x030f00b1,
    runtime_interpreters_head: 40,
    interp_id: 56,
    interp_next: 64,
    interp_threads_head: 72,
    interp_gc: 88,
    thread_interp: 200,
    gc_size: 744,
    gc_collecting: 752,
    gc_frame: Some(760),
    gc_generation_stats_size: Some(768),
    gc_generation_stats: Some(776),
};
