// Generated by gen-offsets-table.py for CPython 3.14.4
// Version hex: 0x030e04f0

use crate::remote_debugging::offsets::offset_table::DebugOffsetsLayout;

pub const LAYOUT: DebugOffsetsLayout = DebugOffsetsLayout {
    version_hex: 0x030e04f0,
    runtime_interpreters_head: 40,
    interp_id: 56,
    interp_next: 64,
    interp_threads_head: 72,
    interp_gc: 88,
    thread_interp: 200,
    gc_size: 648,
    gc_collecting: 656,
    gc_frame: None,
    gc_generation_stats_size: None,
    gc_generation_stats: None,
};
