/* automatically generated by rust-bindgen 0.72.1 */

#![allow(non_snake_case, non_camel_case_types, dead_code, non_upper_case_globals, unused_imports)]

use crate::impl_display_debug_offsets;
use crate::impl_validate_debug_offsets;

pub const _Py_Debug_Cookie: &[u8; 9] = b"xdebugpy\0";
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets {
    pub cookie: [::std::os::raw::c_char; 8usize],
    pub version: u64,
    pub free_threaded: u64,
    pub runtime_state: _Py_DebugOffsets__runtime_state,
    pub interpreter_state: _Py_DebugOffsets__interpreter_state,
    pub thread_state: _Py_DebugOffsets__thread_state,
    pub interpreter_frame: _Py_DebugOffsets__interpreter_frame,
    pub code_object: _Py_DebugOffsets__code_object,
    pub pyobject: _Py_DebugOffsets__pyobject,
    pub type_object: _Py_DebugOffsets__type_object,
    pub tuple_object: _Py_DebugOffsets__tuple_object,
    pub list_object: _Py_DebugOffsets__list_object,
    pub set_object: _Py_DebugOffsets__set_object,
    pub dict_object: _Py_DebugOffsets__dict_object,
    pub float_object: _Py_DebugOffsets__float_object,
    pub long_object: _Py_DebugOffsets__long_object,
    pub bytes_object: _Py_DebugOffsets__bytes_object,
    pub unicode_object: _Py_DebugOffsets__unicode_object,
    pub gc: _Py_DebugOffsets__gc,
    pub gen_object: _Py_DebugOffsets__gen_object,
    pub llist_node: _Py_DebugOffsets__llist_node,
    pub debugger_support: _Py_DebugOffsets__debugger_support,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__runtime_state {
    pub size: u64,
    pub finalizing: u64,
    pub interpreters_head: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _Py_DebugOffsets__runtime_state"]
        [::std::mem::size_of::<_Py_DebugOffsets__runtime_state>() - 24usize];
    ["Alignment of _Py_DebugOffsets__runtime_state"]
        [::std::mem::align_of::<_Py_DebugOffsets__runtime_state>() - 8usize];
    ["Offset of field: _Py_DebugOffsets__runtime_state::size"]
        [::std::mem::offset_of!(_Py_DebugOffsets__runtime_state, size) - 0usize];
    ["Offset of field: _Py_DebugOffsets__runtime_state::finalizing"]
        [::std::mem::offset_of!(_Py_DebugOffsets__runtime_state, finalizing) - 8usize];
    ["Offset of field: _Py_DebugOffsets__runtime_state::interpreters_head"]
        [::std::mem::offset_of!(_Py_DebugOffsets__runtime_state, interpreters_head) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__interpreter_state {
    pub size: u64,
    pub id: u64,
    pub next: u64,
    pub threads_head: u64,
    pub threads_main: u64,
    pub gc: u64,
    pub imports_modules: u64,
    pub sysdict: u64,
    pub builtins: u64,
    pub ceval_gil: u64,
    pub gil_runtime_state: u64,
    pub gil_runtime_state_enabled: u64,
    pub gil_runtime_state_locked: u64,
    pub gil_runtime_state_holder: u64,
    pub code_object_generation: u64,
    pub tlbc_generation: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _Py_DebugOffsets__interpreter_state"]
        [::std::mem::size_of::<_Py_DebugOffsets__interpreter_state>() - 128usize];
    ["Alignment of _Py_DebugOffsets__interpreter_state"]
        [::std::mem::align_of::<_Py_DebugOffsets__interpreter_state>() - 8usize];
    ["Offset of field: _Py_DebugOffsets__interpreter_state::size"]
        [::std::mem::offset_of!(_Py_DebugOffsets__interpreter_state, size) - 0usize];
    ["Offset of field: _Py_DebugOffsets__interpreter_state::id"]
        [::std::mem::offset_of!(_Py_DebugOffsets__interpreter_state, id) - 8usize];
    ["Offset of field: _Py_DebugOffsets__interpreter_state::next"]
        [::std::mem::offset_of!(_Py_DebugOffsets__interpreter_state, next) - 16usize];
    ["Offset of field: _Py_DebugOffsets__interpreter_state::threads_head"]
        [::std::mem::offset_of!(_Py_DebugOffsets__interpreter_state, threads_head) - 24usize];
    ["Offset of field: _Py_DebugOffsets__interpreter_state::threads_main"]
        [::std::mem::offset_of!(_Py_DebugOffsets__interpreter_state, threads_main) - 32usize];
    ["Offset of field: _Py_DebugOffsets__interpreter_state::gc"]
        [::std::mem::offset_of!(_Py_DebugOffsets__interpreter_state, gc) - 40usize];
    ["Offset of field: _Py_DebugOffsets__interpreter_state::imports_modules"]
        [::std::mem::offset_of!(_Py_DebugOffsets__interpreter_state, imports_modules) - 48usize];
    ["Offset of field: _Py_DebugOffsets__interpreter_state::sysdict"]
        [::std::mem::offset_of!(_Py_DebugOffsets__interpreter_state, sysdict) - 56usize];
    ["Offset of field: _Py_DebugOffsets__interpreter_state::builtins"]
        [::std::mem::offset_of!(_Py_DebugOffsets__interpreter_state, builtins) - 64usize];
    ["Offset of field: _Py_DebugOffsets__interpreter_state::ceval_gil"]
        [::std::mem::offset_of!(_Py_DebugOffsets__interpreter_state, ceval_gil) - 72usize];
    ["Offset of field: _Py_DebugOffsets__interpreter_state::gil_runtime_state"]
        [::std::mem::offset_of!(_Py_DebugOffsets__interpreter_state, gil_runtime_state) - 80usize];
    ["Offset of field: _Py_DebugOffsets__interpreter_state::gil_runtime_state_enabled"][::std::mem::offset_of!(
        _Py_DebugOffsets__interpreter_state,
        gil_runtime_state_enabled
    )
        - 88usize];
    ["Offset of field: _Py_DebugOffsets__interpreter_state::gil_runtime_state_locked"][::std::mem::offset_of!(
        _Py_DebugOffsets__interpreter_state,
        gil_runtime_state_locked
    ) - 96usize];
    ["Offset of field: _Py_DebugOffsets__interpreter_state::gil_runtime_state_holder"][::std::mem::offset_of!(
        _Py_DebugOffsets__interpreter_state,
        gil_runtime_state_holder
    )
        - 104usize];
    ["Offset of field: _Py_DebugOffsets__interpreter_state::code_object_generation"][::std::mem::offset_of!(
        _Py_DebugOffsets__interpreter_state,
        code_object_generation
    ) - 112usize];
    ["Offset of field: _Py_DebugOffsets__interpreter_state::tlbc_generation"]
        [::std::mem::offset_of!(_Py_DebugOffsets__interpreter_state, tlbc_generation) - 120usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__thread_state {
    pub size: u64,
    pub prev: u64,
    pub next: u64,
    pub interp: u64,
    pub current_frame: u64,
    pub thread_id: u64,
    pub native_thread_id: u64,
    pub datastack_chunk: u64,
    pub status: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _Py_DebugOffsets__thread_state"]
        [::std::mem::size_of::<_Py_DebugOffsets__thread_state>() - 72usize];
    ["Alignment of _Py_DebugOffsets__thread_state"]
        [::std::mem::align_of::<_Py_DebugOffsets__thread_state>() - 8usize];
    ["Offset of field: _Py_DebugOffsets__thread_state::size"]
        [::std::mem::offset_of!(_Py_DebugOffsets__thread_state, size) - 0usize];
    ["Offset of field: _Py_DebugOffsets__thread_state::prev"]
        [::std::mem::offset_of!(_Py_DebugOffsets__thread_state, prev) - 8usize];
    ["Offset of field: _Py_DebugOffsets__thread_state::next"]
        [::std::mem::offset_of!(_Py_DebugOffsets__thread_state, next) - 16usize];
    ["Offset of field: _Py_DebugOffsets__thread_state::interp"]
        [::std::mem::offset_of!(_Py_DebugOffsets__thread_state, interp) - 24usize];
    ["Offset of field: _Py_DebugOffsets__thread_state::current_frame"]
        [::std::mem::offset_of!(_Py_DebugOffsets__thread_state, current_frame) - 32usize];
    ["Offset of field: _Py_DebugOffsets__thread_state::thread_id"]
        [::std::mem::offset_of!(_Py_DebugOffsets__thread_state, thread_id) - 40usize];
    ["Offset of field: _Py_DebugOffsets__thread_state::native_thread_id"]
        [::std::mem::offset_of!(_Py_DebugOffsets__thread_state, native_thread_id) - 48usize];
    ["Offset of field: _Py_DebugOffsets__thread_state::datastack_chunk"]
        [::std::mem::offset_of!(_Py_DebugOffsets__thread_state, datastack_chunk) - 56usize];
    ["Offset of field: _Py_DebugOffsets__thread_state::status"]
        [::std::mem::offset_of!(_Py_DebugOffsets__thread_state, status) - 64usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__interpreter_frame {
    pub size: u64,
    pub previous: u64,
    pub executable: u64,
    pub instr_ptr: u64,
    pub localsplus: u64,
    pub owner: u64,
    pub stackpointer: u64,
    pub tlbc_index: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _Py_DebugOffsets__interpreter_frame"]
        [::std::mem::size_of::<_Py_DebugOffsets__interpreter_frame>() - 64usize];
    ["Alignment of _Py_DebugOffsets__interpreter_frame"]
        [::std::mem::align_of::<_Py_DebugOffsets__interpreter_frame>() - 8usize];
    ["Offset of field: _Py_DebugOffsets__interpreter_frame::size"]
        [::std::mem::offset_of!(_Py_DebugOffsets__interpreter_frame, size) - 0usize];
    ["Offset of field: _Py_DebugOffsets__interpreter_frame::previous"]
        [::std::mem::offset_of!(_Py_DebugOffsets__interpreter_frame, previous) - 8usize];
    ["Offset of field: _Py_DebugOffsets__interpreter_frame::executable"]
        [::std::mem::offset_of!(_Py_DebugOffsets__interpreter_frame, executable) - 16usize];
    ["Offset of field: _Py_DebugOffsets__interpreter_frame::instr_ptr"]
        [::std::mem::offset_of!(_Py_DebugOffsets__interpreter_frame, instr_ptr) - 24usize];
    ["Offset of field: _Py_DebugOffsets__interpreter_frame::localsplus"]
        [::std::mem::offset_of!(_Py_DebugOffsets__interpreter_frame, localsplus) - 32usize];
    ["Offset of field: _Py_DebugOffsets__interpreter_frame::owner"]
        [::std::mem::offset_of!(_Py_DebugOffsets__interpreter_frame, owner) - 40usize];
    ["Offset of field: _Py_DebugOffsets__interpreter_frame::stackpointer"]
        [::std::mem::offset_of!(_Py_DebugOffsets__interpreter_frame, stackpointer) - 48usize];
    ["Offset of field: _Py_DebugOffsets__interpreter_frame::tlbc_index"]
        [::std::mem::offset_of!(_Py_DebugOffsets__interpreter_frame, tlbc_index) - 56usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__code_object {
    pub size: u64,
    pub filename: u64,
    pub name: u64,
    pub qualname: u64,
    pub linetable: u64,
    pub firstlineno: u64,
    pub argcount: u64,
    pub localsplusnames: u64,
    pub localspluskinds: u64,
    pub co_code_adaptive: u64,
    pub co_tlbc: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _Py_DebugOffsets__code_object"]
        [::std::mem::size_of::<_Py_DebugOffsets__code_object>() - 88usize];
    ["Alignment of _Py_DebugOffsets__code_object"]
        [::std::mem::align_of::<_Py_DebugOffsets__code_object>() - 8usize];
    ["Offset of field: _Py_DebugOffsets__code_object::size"]
        [::std::mem::offset_of!(_Py_DebugOffsets__code_object, size) - 0usize];
    ["Offset of field: _Py_DebugOffsets__code_object::filename"]
        [::std::mem::offset_of!(_Py_DebugOffsets__code_object, filename) - 8usize];
    ["Offset of field: _Py_DebugOffsets__code_object::name"]
        [::std::mem::offset_of!(_Py_DebugOffsets__code_object, name) - 16usize];
    ["Offset of field: _Py_DebugOffsets__code_object::qualname"]
        [::std::mem::offset_of!(_Py_DebugOffsets__code_object, qualname) - 24usize];
    ["Offset of field: _Py_DebugOffsets__code_object::linetable"]
        [::std::mem::offset_of!(_Py_DebugOffsets__code_object, linetable) - 32usize];
    ["Offset of field: _Py_DebugOffsets__code_object::firstlineno"]
        [::std::mem::offset_of!(_Py_DebugOffsets__code_object, firstlineno) - 40usize];
    ["Offset of field: _Py_DebugOffsets__code_object::argcount"]
        [::std::mem::offset_of!(_Py_DebugOffsets__code_object, argcount) - 48usize];
    ["Offset of field: _Py_DebugOffsets__code_object::localsplusnames"]
        [::std::mem::offset_of!(_Py_DebugOffsets__code_object, localsplusnames) - 56usize];
    ["Offset of field: _Py_DebugOffsets__code_object::localspluskinds"]
        [::std::mem::offset_of!(_Py_DebugOffsets__code_object, localspluskinds) - 64usize];
    ["Offset of field: _Py_DebugOffsets__code_object::co_code_adaptive"]
        [::std::mem::offset_of!(_Py_DebugOffsets__code_object, co_code_adaptive) - 72usize];
    ["Offset of field: _Py_DebugOffsets__code_object::co_tlbc"]
        [::std::mem::offset_of!(_Py_DebugOffsets__code_object, co_tlbc) - 80usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__pyobject {
    pub size: u64,
    pub ob_type: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _Py_DebugOffsets__pyobject"]
        [::std::mem::size_of::<_Py_DebugOffsets__pyobject>() - 16usize];
    ["Alignment of _Py_DebugOffsets__pyobject"]
        [::std::mem::align_of::<_Py_DebugOffsets__pyobject>() - 8usize];
    ["Offset of field: _Py_DebugOffsets__pyobject::size"]
        [::std::mem::offset_of!(_Py_DebugOffsets__pyobject, size) - 0usize];
    ["Offset of field: _Py_DebugOffsets__pyobject::ob_type"]
        [::std::mem::offset_of!(_Py_DebugOffsets__pyobject, ob_type) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__type_object {
    pub size: u64,
    pub tp_name: u64,
    pub tp_repr: u64,
    pub tp_flags: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _Py_DebugOffsets__type_object"]
        [::std::mem::size_of::<_Py_DebugOffsets__type_object>() - 32usize];
    ["Alignment of _Py_DebugOffsets__type_object"]
        [::std::mem::align_of::<_Py_DebugOffsets__type_object>() - 8usize];
    ["Offset of field: _Py_DebugOffsets__type_object::size"]
        [::std::mem::offset_of!(_Py_DebugOffsets__type_object, size) - 0usize];
    ["Offset of field: _Py_DebugOffsets__type_object::tp_name"]
        [::std::mem::offset_of!(_Py_DebugOffsets__type_object, tp_name) - 8usize];
    ["Offset of field: _Py_DebugOffsets__type_object::tp_repr"]
        [::std::mem::offset_of!(_Py_DebugOffsets__type_object, tp_repr) - 16usize];
    ["Offset of field: _Py_DebugOffsets__type_object::tp_flags"]
        [::std::mem::offset_of!(_Py_DebugOffsets__type_object, tp_flags) - 24usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__tuple_object {
    pub size: u64,
    pub ob_item: u64,
    pub ob_size: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _Py_DebugOffsets__tuple_object"]
        [::std::mem::size_of::<_Py_DebugOffsets__tuple_object>() - 24usize];
    ["Alignment of _Py_DebugOffsets__tuple_object"]
        [::std::mem::align_of::<_Py_DebugOffsets__tuple_object>() - 8usize];
    ["Offset of field: _Py_DebugOffsets__tuple_object::size"]
        [::std::mem::offset_of!(_Py_DebugOffsets__tuple_object, size) - 0usize];
    ["Offset of field: _Py_DebugOffsets__tuple_object::ob_item"]
        [::std::mem::offset_of!(_Py_DebugOffsets__tuple_object, ob_item) - 8usize];
    ["Offset of field: _Py_DebugOffsets__tuple_object::ob_size"]
        [::std::mem::offset_of!(_Py_DebugOffsets__tuple_object, ob_size) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__list_object {
    pub size: u64,
    pub ob_item: u64,
    pub ob_size: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _Py_DebugOffsets__list_object"]
        [::std::mem::size_of::<_Py_DebugOffsets__list_object>() - 24usize];
    ["Alignment of _Py_DebugOffsets__list_object"]
        [::std::mem::align_of::<_Py_DebugOffsets__list_object>() - 8usize];
    ["Offset of field: _Py_DebugOffsets__list_object::size"]
        [::std::mem::offset_of!(_Py_DebugOffsets__list_object, size) - 0usize];
    ["Offset of field: _Py_DebugOffsets__list_object::ob_item"]
        [::std::mem::offset_of!(_Py_DebugOffsets__list_object, ob_item) - 8usize];
    ["Offset of field: _Py_DebugOffsets__list_object::ob_size"]
        [::std::mem::offset_of!(_Py_DebugOffsets__list_object, ob_size) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__set_object {
    pub size: u64,
    pub used: u64,
    pub table: u64,
    pub mask: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _Py_DebugOffsets__set_object"]
        [::std::mem::size_of::<_Py_DebugOffsets__set_object>() - 32usize];
    ["Alignment of _Py_DebugOffsets__set_object"]
        [::std::mem::align_of::<_Py_DebugOffsets__set_object>() - 8usize];
    ["Offset of field: _Py_DebugOffsets__set_object::size"]
        [::std::mem::offset_of!(_Py_DebugOffsets__set_object, size) - 0usize];
    ["Offset of field: _Py_DebugOffsets__set_object::used"]
        [::std::mem::offset_of!(_Py_DebugOffsets__set_object, used) - 8usize];
    ["Offset of field: _Py_DebugOffsets__set_object::table"]
        [::std::mem::offset_of!(_Py_DebugOffsets__set_object, table) - 16usize];
    ["Offset of field: _Py_DebugOffsets__set_object::mask"]
        [::std::mem::offset_of!(_Py_DebugOffsets__set_object, mask) - 24usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__dict_object {
    pub size: u64,
    pub ma_keys: u64,
    pub ma_values: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _Py_DebugOffsets__dict_object"]
        [::std::mem::size_of::<_Py_DebugOffsets__dict_object>() - 24usize];
    ["Alignment of _Py_DebugOffsets__dict_object"]
        [::std::mem::align_of::<_Py_DebugOffsets__dict_object>() - 8usize];
    ["Offset of field: _Py_DebugOffsets__dict_object::size"]
        [::std::mem::offset_of!(_Py_DebugOffsets__dict_object, size) - 0usize];
    ["Offset of field: _Py_DebugOffsets__dict_object::ma_keys"]
        [::std::mem::offset_of!(_Py_DebugOffsets__dict_object, ma_keys) - 8usize];
    ["Offset of field: _Py_DebugOffsets__dict_object::ma_values"]
        [::std::mem::offset_of!(_Py_DebugOffsets__dict_object, ma_values) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__float_object {
    pub size: u64,
    pub ob_fval: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _Py_DebugOffsets__float_object"]
        [::std::mem::size_of::<_Py_DebugOffsets__float_object>() - 16usize];
    ["Alignment of _Py_DebugOffsets__float_object"]
        [::std::mem::align_of::<_Py_DebugOffsets__float_object>() - 8usize];
    ["Offset of field: _Py_DebugOffsets__float_object::size"]
        [::std::mem::offset_of!(_Py_DebugOffsets__float_object, size) - 0usize];
    ["Offset of field: _Py_DebugOffsets__float_object::ob_fval"]
        [::std::mem::offset_of!(_Py_DebugOffsets__float_object, ob_fval) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__long_object {
    pub size: u64,
    pub lv_tag: u64,
    pub ob_digit: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _Py_DebugOffsets__long_object"]
        [::std::mem::size_of::<_Py_DebugOffsets__long_object>() - 24usize];
    ["Alignment of _Py_DebugOffsets__long_object"]
        [::std::mem::align_of::<_Py_DebugOffsets__long_object>() - 8usize];
    ["Offset of field: _Py_DebugOffsets__long_object::size"]
        [::std::mem::offset_of!(_Py_DebugOffsets__long_object, size) - 0usize];
    ["Offset of field: _Py_DebugOffsets__long_object::lv_tag"]
        [::std::mem::offset_of!(_Py_DebugOffsets__long_object, lv_tag) - 8usize];
    ["Offset of field: _Py_DebugOffsets__long_object::ob_digit"]
        [::std::mem::offset_of!(_Py_DebugOffsets__long_object, ob_digit) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__bytes_object {
    pub size: u64,
    pub ob_size: u64,
    pub ob_sval: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _Py_DebugOffsets__bytes_object"]
        [::std::mem::size_of::<_Py_DebugOffsets__bytes_object>() - 24usize];
    ["Alignment of _Py_DebugOffsets__bytes_object"]
        [::std::mem::align_of::<_Py_DebugOffsets__bytes_object>() - 8usize];
    ["Offset of field: _Py_DebugOffsets__bytes_object::size"]
        [::std::mem::offset_of!(_Py_DebugOffsets__bytes_object, size) - 0usize];
    ["Offset of field: _Py_DebugOffsets__bytes_object::ob_size"]
        [::std::mem::offset_of!(_Py_DebugOffsets__bytes_object, ob_size) - 8usize];
    ["Offset of field: _Py_DebugOffsets__bytes_object::ob_sval"]
        [::std::mem::offset_of!(_Py_DebugOffsets__bytes_object, ob_sval) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__unicode_object {
    pub size: u64,
    pub state: u64,
    pub length: u64,
    pub asciiobject_size: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _Py_DebugOffsets__unicode_object"]
        [::std::mem::size_of::<_Py_DebugOffsets__unicode_object>() - 32usize];
    ["Alignment of _Py_DebugOffsets__unicode_object"]
        [::std::mem::align_of::<_Py_DebugOffsets__unicode_object>() - 8usize];
    ["Offset of field: _Py_DebugOffsets__unicode_object::size"]
        [::std::mem::offset_of!(_Py_DebugOffsets__unicode_object, size) - 0usize];
    ["Offset of field: _Py_DebugOffsets__unicode_object::state"]
        [::std::mem::offset_of!(_Py_DebugOffsets__unicode_object, state) - 8usize];
    ["Offset of field: _Py_DebugOffsets__unicode_object::length"]
        [::std::mem::offset_of!(_Py_DebugOffsets__unicode_object, length) - 16usize];
    ["Offset of field: _Py_DebugOffsets__unicode_object::asciiobject_size"]
        [::std::mem::offset_of!(_Py_DebugOffsets__unicode_object, asciiobject_size) - 24usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__gc {
    pub size: u64,
    pub collecting: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _Py_DebugOffsets__gc"][::std::mem::size_of::<_Py_DebugOffsets__gc>() - 16usize];
    ["Alignment of _Py_DebugOffsets__gc"][::std::mem::align_of::<_Py_DebugOffsets__gc>() - 8usize];
    ["Offset of field: _Py_DebugOffsets__gc::size"]
        [::std::mem::offset_of!(_Py_DebugOffsets__gc, size) - 0usize];
    ["Offset of field: _Py_DebugOffsets__gc::collecting"]
        [::std::mem::offset_of!(_Py_DebugOffsets__gc, collecting) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__gen_object {
    pub size: u64,
    pub gi_name: u64,
    pub gi_iframe: u64,
    pub gi_frame_state: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _Py_DebugOffsets__gen_object"]
        [::std::mem::size_of::<_Py_DebugOffsets__gen_object>() - 32usize];
    ["Alignment of _Py_DebugOffsets__gen_object"]
        [::std::mem::align_of::<_Py_DebugOffsets__gen_object>() - 8usize];
    ["Offset of field: _Py_DebugOffsets__gen_object::size"]
        [::std::mem::offset_of!(_Py_DebugOffsets__gen_object, size) - 0usize];
    ["Offset of field: _Py_DebugOffsets__gen_object::gi_name"]
        [::std::mem::offset_of!(_Py_DebugOffsets__gen_object, gi_name) - 8usize];
    ["Offset of field: _Py_DebugOffsets__gen_object::gi_iframe"]
        [::std::mem::offset_of!(_Py_DebugOffsets__gen_object, gi_iframe) - 16usize];
    ["Offset of field: _Py_DebugOffsets__gen_object::gi_frame_state"]
        [::std::mem::offset_of!(_Py_DebugOffsets__gen_object, gi_frame_state) - 24usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__llist_node {
    pub next: u64,
    pub prev: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _Py_DebugOffsets__llist_node"]
        [::std::mem::size_of::<_Py_DebugOffsets__llist_node>() - 16usize];
    ["Alignment of _Py_DebugOffsets__llist_node"]
        [::std::mem::align_of::<_Py_DebugOffsets__llist_node>() - 8usize];
    ["Offset of field: _Py_DebugOffsets__llist_node::next"]
        [::std::mem::offset_of!(_Py_DebugOffsets__llist_node, next) - 0usize];
    ["Offset of field: _Py_DebugOffsets__llist_node::prev"]
        [::std::mem::offset_of!(_Py_DebugOffsets__llist_node, prev) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__debugger_support {
    pub eval_breaker: u64,
    pub remote_debugger_support: u64,
    pub remote_debugging_enabled: u64,
    pub debugger_pending_call: u64,
    pub debugger_script_path: u64,
    pub debugger_script_path_size: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _Py_DebugOffsets__debugger_support"]
        [::std::mem::size_of::<_Py_DebugOffsets__debugger_support>() - 48usize];
    ["Alignment of _Py_DebugOffsets__debugger_support"]
        [::std::mem::align_of::<_Py_DebugOffsets__debugger_support>() - 8usize];
    ["Offset of field: _Py_DebugOffsets__debugger_support::eval_breaker"]
        [::std::mem::offset_of!(_Py_DebugOffsets__debugger_support, eval_breaker) - 0usize];
    ["Offset of field: _Py_DebugOffsets__debugger_support::remote_debugger_support"][::std::mem::offset_of!(
        _Py_DebugOffsets__debugger_support,
        remote_debugger_support
    ) - 8usize];
    ["Offset of field: _Py_DebugOffsets__debugger_support::remote_debugging_enabled"][::std::mem::offset_of!(
        _Py_DebugOffsets__debugger_support,
        remote_debugging_enabled
    ) - 16usize];
    ["Offset of field: _Py_DebugOffsets__debugger_support::debugger_pending_call"][::std::mem::offset_of!(
        _Py_DebugOffsets__debugger_support,
        debugger_pending_call
    ) - 24usize];
    ["Offset of field: _Py_DebugOffsets__debugger_support::debugger_script_path"][::std::mem::offset_of!(
        _Py_DebugOffsets__debugger_support,
        debugger_script_path
    ) - 32usize];
    ["Offset of field: _Py_DebugOffsets__debugger_support::debugger_script_path_size"][::std::mem::offset_of!(
        _Py_DebugOffsets__debugger_support,
        debugger_script_path_size
    ) - 40usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _Py_DebugOffsets"][::std::mem::size_of::<_Py_DebugOffsets>() - 760usize];
    ["Alignment of _Py_DebugOffsets"][::std::mem::align_of::<_Py_DebugOffsets>() - 8usize];
    ["Offset of field: _Py_DebugOffsets::cookie"]
        [::std::mem::offset_of!(_Py_DebugOffsets, cookie) - 0usize];
    ["Offset of field: _Py_DebugOffsets::version"]
        [::std::mem::offset_of!(_Py_DebugOffsets, version) - 8usize];
    ["Offset of field: _Py_DebugOffsets::free_threaded"]
        [::std::mem::offset_of!(_Py_DebugOffsets, free_threaded) - 16usize];
    ["Offset of field: _Py_DebugOffsets::runtime_state"]
        [::std::mem::offset_of!(_Py_DebugOffsets, runtime_state) - 24usize];
    ["Offset of field: _Py_DebugOffsets::interpreter_state"]
        [::std::mem::offset_of!(_Py_DebugOffsets, interpreter_state) - 48usize];
    ["Offset of field: _Py_DebugOffsets::thread_state"]
        [::std::mem::offset_of!(_Py_DebugOffsets, thread_state) - 176usize];
    ["Offset of field: _Py_DebugOffsets::interpreter_frame"]
        [::std::mem::offset_of!(_Py_DebugOffsets, interpreter_frame) - 248usize];
    ["Offset of field: _Py_DebugOffsets::code_object"]
        [::std::mem::offset_of!(_Py_DebugOffsets, code_object) - 312usize];
    ["Offset of field: _Py_DebugOffsets::pyobject"]
        [::std::mem::offset_of!(_Py_DebugOffsets, pyobject) - 400usize];
    ["Offset of field: _Py_DebugOffsets::type_object"]
        [::std::mem::offset_of!(_Py_DebugOffsets, type_object) - 416usize];
    ["Offset of field: _Py_DebugOffsets::tuple_object"]
        [::std::mem::offset_of!(_Py_DebugOffsets, tuple_object) - 448usize];
    ["Offset of field: _Py_DebugOffsets::list_object"]
        [::std::mem::offset_of!(_Py_DebugOffsets, list_object) - 472usize];
    ["Offset of field: _Py_DebugOffsets::set_object"]
        [::std::mem::offset_of!(_Py_DebugOffsets, set_object) - 496usize];
    ["Offset of field: _Py_DebugOffsets::dict_object"]
        [::std::mem::offset_of!(_Py_DebugOffsets, dict_object) - 528usize];
    ["Offset of field: _Py_DebugOffsets::float_object"]
        [::std::mem::offset_of!(_Py_DebugOffsets, float_object) - 552usize];
    ["Offset of field: _Py_DebugOffsets::long_object"]
        [::std::mem::offset_of!(_Py_DebugOffsets, long_object) - 568usize];
    ["Offset of field: _Py_DebugOffsets::bytes_object"]
        [::std::mem::offset_of!(_Py_DebugOffsets, bytes_object) - 592usize];
    ["Offset of field: _Py_DebugOffsets::unicode_object"]
        [::std::mem::offset_of!(_Py_DebugOffsets, unicode_object) - 616usize];
    ["Offset of field: _Py_DebugOffsets::gc"]
        [::std::mem::offset_of!(_Py_DebugOffsets, gc) - 648usize];
    ["Offset of field: _Py_DebugOffsets::gen_object"]
        [::std::mem::offset_of!(_Py_DebugOffsets, gen_object) - 664usize];
    ["Offset of field: _Py_DebugOffsets::llist_node"]
        [::std::mem::offset_of!(_Py_DebugOffsets, llist_node) - 696usize];
    ["Offset of field: _Py_DebugOffsets::debugger_support"]
        [::std::mem::offset_of!(_Py_DebugOffsets, debugger_support) - 712usize];
};
pub type Py_ssize_t = ::std::os::raw::c_longlong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct gc_generation_stats {
    pub collections: Py_ssize_t,
    pub collected: Py_ssize_t,
    pub uncollectable: Py_ssize_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of gc_generation_stats"][::std::mem::size_of::<gc_generation_stats>() - 24usize];
    ["Alignment of gc_generation_stats"][::std::mem::align_of::<gc_generation_stats>() - 8usize];
    ["Offset of field: gc_generation_stats::collections"]
        [::std::mem::offset_of!(gc_generation_stats, collections) - 0usize];
    ["Offset of field: gc_generation_stats::collected"]
        [::std::mem::offset_of!(gc_generation_stats, collected) - 8usize];
    ["Offset of field: gc_generation_stats::uncollectable"]
        [::std::mem::offset_of!(gc_generation_stats, uncollectable) - 16usize];
};


// -- GC generation stats field layout --
// Computed from bindgen-generated #[repr(C)] struct via offset_of! at compile time.

pub use crate::remote_debugging::offsets::offset_table::GcItemLayout;

pub const GC_ITEM_SIZE: usize = std::mem::size_of::<gc_generation_stats>();

pub static GC_LAYOUT: GcItemLayout = GcItemLayout {
    item_size: GC_ITEM_SIZE,
    fields: &[
        ("collections", std::mem::offset_of!(gc_generation_stats, collections)),
        ("collected", std::mem::offset_of!(gc_generation_stats, collected)),
        ("uncollectable", std::mem::offset_of!(gc_generation_stats, uncollectable)),
    ],
};

pub fn gc_field_names() -> &'static [(&'static str, usize)] {
    GC_LAYOUT.fields
}

/// Byte offset of the inline `generation_stats[]` array within `_gc_runtime_state`,
/// computed by scripts/gen-offsets.py from this build's headers (version-specific).
pub const GC_STATS_INLINE_OFF: u64 = 0x78;

// -- DebugOffsetsView: per-version dispatch (see offsets/mod.rs) --
impl crate::remote_debugging::offsets::DebugOffsetsView for _Py_DebugOffsets {
    fn layout_version(&self) -> u64 { 0x030e04f0 }
    fn threads_main(&self) -> u64 { self.interpreter_state.threads_main }
    fn gc_frame(&self) -> u64 { 0 }
    fn gc_generation_stats(&self) -> u64 { 0 }
    fn gc_generation_stats_size(&self) -> u64 { 0 }
    fn gc_stats_shape(&self) -> crate::remote_debugging::offsets::GcStatsShape {
        crate::remote_debugging::offsets::GcStatsShape {
            kind: crate::remote_debugging::offsets::offset_table::GcStatsKind::InlineArray,
            item_size: GC_ITEM_SIZE as u64,
            layout: Some(&GC_LAYOUT),
        }
    }
    fn gc_inline_off(&self) -> u64 { GC_STATS_INLINE_OFF }
}
